site_name: CIM for Norway

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 ElBits AS

theme:
  name: material # Specifies that the material theme is used.
  custom_dir: overrides
  favicon: images/cim4nologo.svg
  logo: images/cim4nologo.svg
  features: # Enables optional features provided by the material theme.
    - navigation.tabs # Organizes the top-level navigation into tabs.
    # - navigation.expand # Allows the navigation to expand automatically as users drill down into sections. This is annoying.
    - navigation.sections # Adds grouping sections within navigation.
    - navigation.top # Positions navigation links at the top of the page.
    # - toc.integrate # Integrates the table of contents within the main content area. This is annoying.
    # - navigation.footer # Adds navigation links to the footer.
    - search.suggest # Enables search suggestions.
    - search.highlight # Highlights search terms in results.
    - content.tabs.link # Enables linking directly to tabs in the documentation.
    - content.code.annotation # Adds annotations to code blocks.
    - content.code.copy # Adds a copy-to-clipboard button to code blocks.
  language: en # Sets the language to English.
  palette: # Defines color schemes and toggling options between light and dark mode.
    - scheme: default # Define color schemes light
      toggle: # Configures the dark mode toggle with icons and labels.
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black # Set primary color for scheme.
      accent: red # Set accent color for scheme.
    - scheme: slate # Define color schemes Dark
      toggle: # Configures the dark mode toggle with icons and labels.
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black # Set primary color for scheme.
      accent: green # Set accent color for scheme.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/3lbits/NoCIMExtensions
    - icon: fontawesome/solid/file
      link: https://github.com/3lbits/CIM4NoUtility/tree/main

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md

  - Model:

    - Profiles:

      - AviationObstacle:
        - AbstractClasses:
          - IdentifiedObject: Model/Profiles/AviationObstacle/AbstractClasses/IdentifiedObject.md
          - PowerSystemResource: Model/Profiles/AviationObstacle/AbstractClasses/PowerSystemResource.md
        - ConcreteClasses:
          - ACLineSegment: Model/Profiles\AviationObstacle\ConcreteClasses\ACLineSegment.md
          - ACLineSegmentSpan: Model/Profiles\AviationObstacle\ConcreteClasses\ACLineSegmentSpan.md
        - Enumerations:
          - enumeration: Model/Profiles\AviationObstacle\Enumerations\enumeration.md
        - Types:
          - types: Model/Profiles/AviationObstacle/Types/types.md
      
      - WattApp:
        - AbstractClasses:
          - IdentifiedObject: Model/Profiles/WattApp/AbstractClasses/IdentifiedObject.md
          - PowerSystemResource: Model/Profiles/WattApp/AbstractClasses/PowerSystemResource.md
        - ConcreteClasses:
          - ACLineSegment: Model/Profiles\WattApp\ConcreteClasses\ACLineSegment.md
          - ACLineSegmentSpan: Model/Profiles\WattApp\ConcreteClasses\ACLineSegmentSpan.md
        - Enumerations:
          - enumeration: Model/Profiles\WattApp\Enumerations\enumeration.md
        - Types:
          - types: Model/Profiles/WattApp/Types/types.md